# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a39ed8f341968bc61fd23b10f69457d73c54da1c4ab219c9f42a427ee9894f2dc14d87f5ecd20a048b5da71029fbae5e7c926c422e8abc138cda80903fcd1bb

test:
  secret_key_base: 6d9604f924ce66959484bda5f6c3c901380b4100935883fabbe0f105c738d5cfa4cb66908d1953b8c845eaa0ebfa8da1e5e10a4704189ae8ef79a712031e5caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
